services:
  db:
    container_name: security-db
    image: postgres:17
    environment:
      POSTGRES_DB: fergie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
